# Configuration for Ghostty, the GPU enhanced terminal emulator.
#
# Purpose:
# - Configures Ghostty terminal with focus on performance and aesthetics
# - Sets up consistent development environment
# - Provides efficient keyboard-driven workflow
#
# Features:
# - Theme: Rose Pine for elegant, low-contrast visuals
# - Fonts:
#   - Primary: SpaceMono Nerd Font
#   - Bold: Fira Code
#   - Italic: Maple Mono
# - Window:
#   - Clean design with transparent titlebar
#   - Balanced padding for comfort
#   - State persistence between sessions
#
# Integration:
# - Extensive keyboard shortcuts with cmd+s leader key
# - Tab and split management for multi-workspace flow
# - Supports Nerd Font symbols for prompt
#
# Performance:
# - GPU-accelerated rendering
# - Clipboard integration with copy-on-select
# - Shell integration with cursor and sudo features

# Fonts
font-family = "SpaceMono Nerd Font"
font-family-bold = "Fira Code Nerd Font"
font-family-italic = "Maple Mono"
font-family-bold-italic = "Maple Mono"
font-size = 15
adjust-underline-position = 4

# Theme
theme = "rose-pine"

selection-background = "#403d52"

# Mouse
mouse-hide-while-typing = true

window-padding-balance = true
window-save-state = "always"
macos-titlebar-style = "transparent"

# other
copy-on-select = "clipboard"
shell-integration-features = "no-cursor,sudo,no-title"

keybindings = {
    "cmd+s>r"="reload_config"
    "cmd+s>x"="close_surface"
    "cmd+s>n"="new_window"
    "cmd+s>c"="new_tab"
    "cmd+s>shift+l"="next_tab"
    "cmd+s>shift+h"="previous_tab"
    "cmd+s>comma"="move_tab:-1"
    "cmd+s>period"="move_tab:1"
    "cmd+s>1"="goto_tab:1"
    "cmd+s>2"="goto_tab:2"
    "cmd+s>3"="goto_tab:3"
    "cmd+s>4"="goto_tab:4"
    "cmd+s>5"="goto_tab:5"
    "cmd+s>6"="goto_tab:6"
    "cmd+s>7"="goto_tab:7"
    "cmd+s>8"="goto_tab:8"
    "cmd+s>9"="goto_tab:9"
    "cmd+s>\\"="new_split:right"
    "cmd+s>-"="new_split:down"
    "cmd+s>j"="goto_split:bottom"
    "cmd+s>k"="goto_split:top"
    "cmd+s>h"="goto_split:left"
    "cmd+s>l"="goto_split:right"
    "cmd+s>z"="toggle_split_zoom"
    "cmd+s>e"="equalize_splits"
}
