# Configuration for Ghostty, the GPU enhanced terminal emulator.
#
# Purpose:
# - Configures Ghostty terminal with focus on performance and aesthetics
# - Sets up consistent development environment
# - Provides efficient keyboard-driven workflow
#
# Features:
# - Theme: Rose Pine for elegant, low-contrast visuals
# - Fonts:
#   - Primary: SpaceMono Nerd Font
#   - Bold: Fira Code
#   - Italic: Maple Mono
# - Window:
#   - Clean design with transparent titlebar
#   - Balanced padding for comfort
#   - State persistence between sessions
#
# Integration:
# - Extensive keyboard shortcuts with cmd+s leader key
# - Tab and split management for multi-workspace flow
# - Supports Nerd Font symbols for prompt
#
# Performance:
# - GPU-accelerated rendering
# - Clipboard integration with copy-on-select
# - Shell integration with cursor and sudo features

# Fonts
font-family = "SpaceMono Nerd Font"
font-family-bold = "Fira Code"
font-family-italic = "Maple Mono"
font-family-bold-italic = "Maple Mono"
font-size = 15
adjust-underline-position = 4

# Theme
theme = rose-pine

selection-background = #403d52

# Mouse
mouse-hide-while-typing = true

window-padding-balance = true
window-save-state = always
macos-titlebar-style=transparent

# keybindings
keybind = cmd+s>r=reload_config
keybind = cmd+s>x=close_surface

keybind = cmd+s>n=new_window

# tabs
keybind = cmd+s>c=new_tab
keybind = cmd+s>shift+l=next_tab
keybind = cmd+s>shift+h=previous_tab
keybind = cmd+s>comma=move_tab:-1
keybind = cmd+s>period=move_tab:1

# quick tab switch
keybind = cmd+s>1=goto_tab:1
keybind = cmd+s>2=goto_tab:2
keybind = cmd+s>3=goto_tab:3
keybind = cmd+s>4=goto_tab:4
keybind = cmd+s>5=goto_tab:5
keybind = cmd+s>6=goto_tab:6
keybind = cmd+s>7=goto_tab:7
keybind = cmd+s>8=goto_tab:8
keybind = cmd+s>9=goto_tab:9

# split
keybind = cmd+s>\=new_split:right
keybind = cmd+s>-=new_split:down

keybind = cmd+s>j=goto_split:bottom
keybind = cmd+s>k=goto_split:top
keybind = cmd+s>h=goto_split:left
keybind = cmd+s>l=goto_split:right

keybind = cmd+s>z=toggle_split_zoom

keybind = cmd+s>e=equalize_splits

# other
copy-on-select = clipboard
shell-integration-features = no-cursor,sudo,no-title
