# Configuration for Ghostty, the GPU enhanced terminal emulator.
#
# Purpose:
# - Configures Ghostty terminal with focus on performance and aesthetics
# - Sets up consistent development environment
# - Provides efficient keyboard-driven workflow
#
# Features:
# - Theme: Rose Pine for elegant, low-contrast visuals
# - Fonts:
#   - Primary: SpaceMono Nerd Font
#   - Bold: Fira Code
#   - Italic: Maple Mono
# - Window:
#   - Clean design with transparent titlebar
#   - Balanced padding for comfort
#   - State persistence between sessions
#
# Integration:
# - Extensive keyboard shortcuts with cmd+s leader key
# - Tab and split management for multi-workspace flow
# - Supports Nerd Font symbols for prompt
#
# Performance:
# - GPU-accelerated rendering
# - Clipboard integration with copy-on-select
# - Shell integration with cursor and sudo features

# Fonts
font-family = "SpaceMono Nerd Font"
font-family-bold = "Fira Code Nerd Font"
font-family-italic = "Maple Mono Nerd Font"
font-family-bold-italic = "Maple Mono Nerd Font"
font-size = 15
adjust-underline-position = 4

# Theme
theme = "rose-pine"

selection-background = "#403d52"

# Mouse
mouse-hide-while-typing = true

window-padding-balance = true
window-save-state = "always"
macos-titlebar-style = "transparent"

# other
copy-on-select = "clipboard"
shell-integration-features = "no-cursor,sudo,no-title"
